name: terraform-plan
description: https://github.com/champtitles/action-terraform-plan
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # global defaults for terraform automation
        export TF_INPUT=${TF_INPUT:-false}
        export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
        export TF_VAR_branch=$(git branch --show-current)
        export TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')

        # load terraform files stored in this action
        cp ${GITHUB_ACTION_PATH}/*.tf .

        # enable cloning of private modules
        if [ -n "${SSH_PRIVATE_KEY}" ]; then
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
        fi

        # execute terraform commands
        terraform init -backend-config key=${TF_VAR_git} -backend-config bucket=${TF_STATE_BUCKET}
        terraform plan
        cd .. && terraform fmt -recursive -check
