name: Terraform Plan

on:
  workflow_call:
    inputs:
      TF_STATE_BUCKET:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.15.1

      - name: set up env
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cp ${GITHUB_ACTION_PATH}/*.tf .

          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

          echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
          echo "TF_INPUT=false" >> $GITHUB_ENV
          echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV
          echo "TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: terraform init
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: terraform init -backend-config key=${TF_VAR_git} -backend-config bucket=${{ inputs.TF_STATE_BUCKET }}

      - name: terraform plan
        run: terraform plan